### ISSUE TITLE
Format price with Rupiah

### ISSUE THREAD

**Issue by mhaidarhanif** [Leads-org/petstop#13]
Format price with Rupiah

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

**Comment by makmuremha** [comment]
> Format price with Rupiah
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat

udah di update
